# Copyright 2025 The Bazel Authors.
# Copyright 2026 JetBrains s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Derived from: https://github.com/bazelbuild/intellij/blob/5ec21e640ed59b316b58559d8e79cb0858e519bd/aspect/intellij_info_impl.bzl

load("//common:common.bzl", "intellij_common")
load("//common:dependencies.bzl", "intellij_deps")
load("//common:ide_info.bzl", "ide_info")
load("//common:output_groups.bzl", "intellij_output_groups")
load("//common:provider.bzl", "intellij_provider")
load(":provider.bzl", "intellij_info_builder")

# compile time dependencies collected for every target
COMPILE_TIME_DEPS = ["deps"]

# Rule kinds to include in outputs, even though no special information is available
EXTRA_RULES = ["sh_binary", "sh_library", "genrule", "intellij_plugin_debug_target", "_plugin_deploy_zip", "intellij_plugin_zip"]

def _merge_dependencies(builder, ctx):
    """Adds information from all dependencies' intellij info providers."""
    for name in dir(ctx.rule.attr):
        for dep in intellij_common.attr_as_label_list(ctx, name):
            if not intellij_provider.IntelliJInfo in dep:
                continue

            intellij_info_builder.append_outputs(builder, dep[intellij_provider.IntelliJInfo])

    # toolchains attribute only available in Bazel 8+
    toolchains = getattr(ctx.rule, "toolchains", None)
    if not toolchains:
        return

    for toolchain_type in ctx.attr._toolchains:
        label = toolchain_type.label

        # it is save to assume that every toolchain carries our provider
        if label in toolchains:
            intellij_info_builder.append(builder, toolchains[label][intellij_provider.IntelliJInfo])

def _serialize_dependencies(builder):
    """Serializes all dependencies currently tracked by the builder."""
    return depset([
        struct(target = dep.key, dependency_type = key)
        for key, list_of_sets in builder.dependencies.items()
        for set in list_of_sets
        for dep in set.to_list()
    ]).to_list()

def _run_modules(target, ctx):
    """Runs all available modules in the order they are defined in intellij_provider."""
    container = ctx.attr._container

    results = {}
    for provider in intellij_provider.ORDERED:
        if provider not in container:
            continue

        module = container[provider]
        result = module.func(target, ctx, results)

        if result:
            results[provider] = result

    return results

def _merge_target_info(builder, target, ctx, results):
    """Adds information collected from the current target's module providers."""
    container = ctx.attr._container

    if AnalysisTestResultInfo in target:
        # We are not allowed to create an action (including a file-write action) for a target
        # defined by an analysis-test rule.
        return

    info = {
        container[provider].field: result.value
        for (provider, result) in results.items()
        if container[provider].field
    }

    # do not generate a intellij-info.txt if there is no language module attached
    if (not info) and (not ctx.rule.kind in EXTRA_RULES):
        return

    # iterate over all providers that could be generated by a module aspect
    for result in results.values():
        intellij_info_builder.append(builder, result)

    info["deps"] = _serialize_dependencies(builder)

    # generate the target key based on the information currently accumulated by the builder
    key = intellij_info_builder.build_target_key(builder, target, ctx)

    # Materialize generated sources
    intellij_info_builder.append_output(
        builder,
        intellij_output_groups.BUILD,
        [
            file
            for target in intellij_common.attr_as_label_list(ctx, "srcs")
            for file in (target[DefaultInfo].files or depset()).to_list()
            if not file.is_source
        ],
    )

    # dependencies have to be serialized last because they might be updated by module providers
    # write the ide info to file and add the generated file to the appropriate output group
    intellij_info_builder.append_ide_infos(builder, [ide_info.write(target, ctx, key, info)])

def _implemenation(target, ctx):
    builder = intellij_info_builder.create()

    intellij_info_builder.append_dependencies(
        builder,
        intellij_deps.COMPILE_TIME,
        intellij_deps.collect(ctx, COMPILE_TIME_DEPS),
    )

    intellij_info_builder.append_dependencies(
        builder,
        intellij_deps.TOOLCHAIN,
        intellij_deps.collect_toolchains(ctx, ctx.attr._toolchains),
    )

    results = _run_modules(target, ctx)

    _merge_target_info(builder, target, ctx, results)
    _merge_dependencies(builder, ctx)

    intellij_info = intellij_info_builder.build(builder, target, ctx, results)

    # Alternative discovery protocol: a client requests the hidden transitive alias (built, but
    # not reported) together with the direct group, which only names the nearest info files.
    outputs = dict(intellij_info.outputs)
    info_outputs = outputs.get(intellij_output_groups.INFO)
    if info_outputs:
        outputs[intellij_output_groups.HIDDEN_INFO] = info_outputs

    return [intellij_info, OutputGroupInfo(**outputs)]

def _unique_flatten(modules, field):
    unique = []
    for module in modules:
        for value in getattr(module, field):
            if value not in unique:
                unique.append(value)

    return unique

def intellij_configure_aspect(modules, container):
    """Creates an aspect running the given module groups."""
    toolchains = _unique_flatten(modules, "toolchains")
    aspect_providers = _unique_flatten(modules, "aspect_providers")
    direct_toolchain_deps = _unique_flatten(modules, "direct_toolchain_deps_do_not_use")

    return intellij_common.aspect(
        implementation = _implemenation,
        fragments = _unique_flatten(modules, "fragments"),
        provides = [intellij_provider.IntelliJInfo],
        attr_aspects = ["*"],
        toolchains_aspects = [str(it) for it in toolchains],
        required_aspect_providers = [[it] for it in aspect_providers],
        # TODO: remove this once all modules have been fixed
        toolchains = [config_common.toolchain_type(it, mandatory = False) for it in direct_toolchain_deps],
        attrs = {
            "_container": attr.label(
                default = container,
                aspects = [it.aspect for it in modules],
            ),
            "_toolchains": attr.label_list(
                default = toolchains,
            ),
        },
    )
